//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NguyenNhutDuy_2122110447.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int id { get; set; }
        public int category_id { get; set; }
        public int brand_id { get; set; }
        public string name { get; set; }
        public string image { get; set; }
        public string detail { get; set; }
        public double price { get; set; }
        public Nullable<double> price_sale { get; set; }
    }
}
